meta_product_name: "Sounds Good"
meta_title: "Sounds Good - Find musicians close to you!"
meta_description: "Start playing with different people."
meta_image: "soundsgoodmeta.png" # should exist in `app/assets/images/`

